In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df=pd.read_csv("cleaned df2.csv")

In [3]:
df

Unnamed: 0  SalePrice  MachineID  ModelID  datasource  auctioneerID  \
0                0      66000     999089     3157         121           3.0   
1                1      57000     117657       77         121           3.0   
2                2      10000     434808     7009         121           3.0   
3                3      38500    1026470      332         121           3.0   
4                4      11000    1057373    17311         121           3.0   
...            ...        ...        ...      ...         ...           ...   
401120      401120      10500    1840702    21439         149           1.0   
401121      401121      11000    1830472    21439         149           1.0   
401122      401122      11500    1887659    21439         149           1.0   
401123      401123       9000    1903570    21435         149           2.0   
401124      401124       7750    1926965    21435         149           2.0   

        YearMade    saledate fiModelDesc fiBaseModel  \
0         2004.0  2006-11-16        521D         521   
1         1996.0  2004-03-26      950FII         950   
2         2001.0  2004-02-26         226         226   
3         2001.0  2011-05-19    PC120-6E       PC120   
4         2007.0  2009-07-23        S175        S175   
...          ...         ...         ...         ...   
401120    2005.0  2011-11-02       35NX2          35   
401121    2005.0  2011-11-02       35NX2          35   
401122    2005.0  2011-11-02       35NX2          35   
401123    2005.0  2011-10-25        30NX          30   
401124    2005.0  2011-10-25        30NX          30   

                                       fiProductClassDesc           state  \
0                Wheel Loader - 110.0 to 120.0 Horsepower         Alabama   
1                Wheel Loader - 150.0 to 175.0 Horsepower  North Carolina   
2       Skid Steer Loader - 1351.0 to 1601.0 Lb Operat...        New York   
3       Hydraulic Excavator, Track - 12.0 to 14.0 Metr...           Texas   
4       Skid Steer Loader - 1601.0 to 1751.0 Lb Operat...        New York   
...                                                   ...             ...   
401120  Hydraulic Excavator, Track - 3.0 to 4.0 Metric...        Maryland   
401121  Hydraulic Excavator, Track - 3.0 to 4.0 Metric...        Maryland   
401122  Hydraulic Excavator, Track - 3.0 to 4.0 Metric...        Maryland   
401123  Hydraulic Excavator, Track - 2.0 to 3.0 Metric...         Florida   
401124  Hydraulic Excavator, Track - 2.0 to 3.0 Metric...         Florida   

       ProductGroup    ProductGroupDesc   Enclosure Hydraulics        Date  \
0                WL        Wheel Loader  EROPS w AC    2 Valve  2006-11-16   
1                WL        Wheel Loader  EROPS w AC    2 Valve  2004-03-26   
2               SSL  Skid Steer Loaders       OROPS  Auxiliary  2004-02-26   
3               TEX    Track Excavators  EROPS w AC    2 Valve  2011-05-19   
4               SSL  Skid Steer Loaders       EROPS  Auxiliary  2009-07-23   
...             ...                 ...         ...        ...         ...   
401120          TEX    Track Excavators       EROPS  Auxiliary  2011-11-02   
401121          TEX    Track Excavators       EROPS   Standard  2011-11-02   
401122          TEX    Track Excavators       EROPS  Auxiliary  2011-11-02   
401123          TEX    Track Excavators       EROPS   Standard  2011-10-25   
401124          TEX    Track Excavators       EROPS   Standard  2011-10-25   

        Month  Year      Time  
0          11  2006  00:00:00  
1           3  2004  00:00:00  
2           2  2004  00:00:00  
3           5  2011  00:00:00  
4           7  2009  00:00:00  
...       ...   ...       ...  
401120     11  2011  00:00:00  
401121     11  2011  00:00:00  
401122     11  2011  00:00:00  
401123     10  2011  00:00:00  
401124     10  2011  00:00:00  

[401125 rows x 20 columns]

df

In [4]:
X=df[['YearMade','ModelID','datasource','auctioneerID','Month','Year','ProductGroup','ProductGroupDesc']]
y=df[['SalePrice']]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [7]:
ohe=OneHotEncoder()
ohe.fit(X[['YearMade','ModelID','datasource','auctioneerID','Month','Year','ProductGroup','ProductGroupDesc']])

OneHotEncoder()

In [8]:
ohe.categories_

[array([1971.        , 1972.        , 1973.        , 1974.        ,
        1975.        , 1976.        , 1977.        , 1978.        ,
        1979.        , 1980.        , 1981.        , 1982.        ,
        1983.        , 1984.        , 1985.        , 1986.        ,
        1987.        , 1988.        , 1989.        , 1990.        ,
        1991.        , 1992.        , 1993.        , 1994.        ,
        1994.38340979, 1995.        , 1996.        , 1997.        ,
        1998.        , 1999.        , 2000.        , 2001.        ,
        2002.        , 2003.        , 2004.        , 2005.        ,
        2006.        , 2007.        , 2008.        , 2009.        ,
        2010.        , 2011.        , 2012.        , 2013.        ]),
 array([   28,    29,    31, ..., 37196, 37197, 37198], dtype=int64),
 array([121, 132, 136, 149, 172], dtype=int64),
 array([1.        , 1.68394446, 2.        , 3.        , 4.        ,
        5.        ]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9

In [9]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_ ),['YearMade','ModelID','datasource','auctioneerID','Month','Year','ProductGroup','ProductGroupDesc']),
                                    remainder='passthrough')

In [10]:
lr=LinearRegression()

In [11]:
pipe=make_pipeline(column_trans,lr)

In [12]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([1971.        , 1972.        , 1973.        , 1974.        ,
       1975.        , 1976.        , 1977.        , 1978.        ,
       1979.        , 1980.        , 1981.        , 1982.        ,
       1983.        , 1984.        , 1985.        , 1986.        ,
       1987.        , 1988.        , 1989.        , 1990.        ,
       1991.        , 1992.        , 1993.        , 1994.        ,
       1994.38340979, 1995.        , 1996.        , 1997.        ,
       1998.        , 1999.        , 2000.        , 2001.        ,
       2002.        , 2...
       2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011], dtype=int64),
                                                                            array(['BL', 'MG', 

In [15]:
y_pred=pipe.predict(X_test)

In [16]:
r2_score(y_test,y_pred)

0.8096369904298646

In [18]:
scores=[]
for i in range(10):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [19]:
np.argmax(scores)

1

In [20]:
scores[np.argmax(scores)]

0.8109381386613198

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8109381386613198

In [22]:
import pickle

In [23]:
pickle.dump(pipe,open("LinearRegression.pk1","wb"))

In [26]:
pipe.predict(pd.DataFrame([[2001.0,7009,121,3.0,2,2004,'SSL','Skid Steer Loaders']],columns=['YearMade','ModelID','datasource','auctioneerID','Month','Year','ProductGroup','ProductGroupDesc']))

array([[15845.00996602]])